[package]
name = "asdecided-desktop-backend"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
rac-engine = { package = "asdecided-core", git = "https://github.com/asdecided/core", rev = "d44a4d739527b9c975d8dcee7fb26be7aae4897f" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

tempfile = "3"
fs2 = "0.4"
similar = "2"
